name: cli_gen
description: Build cli applications using code generation and macros.
version: 0.1.0-dev.3
homepage: https://github.com/pattobrien/cli-gen
repository: https://github.com/pattobrien/cli-gen
issue_tracker: https://github.com/pattobrien/cli-gen/issues

topics:
  - cli
  - args
  - codegen
  - macros

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  cli_annotations: ^0.1.0-dev.3
  code_builder: ^4.10.0
  dart_style: ^2.3.4
  meta: ^1.12.0
  recase: ^4.1.0
  source_gen: ^1.5.0

dev_dependencies:
  checks: ^0.3.0
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.7.2
