name: cli_gen
description: |
  Build CLI applications from plain Dart classes and functions, 
  with the help of code generation.
version: 0.1.0-dev.6
homepage: https://github.com/pattobrien/cli-gen
repository: https://github.com/pattobrien/cli-gen
issue_tracker: https://github.com/pattobrien/cli-gen/issues

topics:
  - cli
  - args
  - codegen
  - macros

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  analyzer: ^6.8.0
  build: ^2.4.1
  cli_annotations: ^0.1.0-dev.6
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  meta: ^1.16.0
  recase: ^4.1.0
  source_gen: ^1.5.0

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  test: ^1.25.9
  coverage: ^1.11.0
  build_runner: ^2.4.13
