name: cli_gen
description: A sample command-line application.
version: 0.1.0-dev.1

environment:
  sdk: ^3.2.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  cli_annotations:
    path: ../cli_annotations
  code_builder: ^4.10.0
  dart_style: ^2.3.4
  meta: ^1.12.0
  recase: ^4.1.0
  source_gen: ^1.5.0

dev_dependencies:
  example_project:
    path: test/example_project
  checks: ^0.3.0
  lints: ^3.0.0
  test: ^1.24.0
