name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-82.0.dev

dependencies:
  args: ^2.4.2
  cli_annotations:
    path: ../src/cli_annotations

dev_dependencies:
  build_runner: ^2.4.8
  cli_gen:
    path: ../src/cli_gen
  lints: ^3.0.0
  test: ^1.24.0
