name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  cli_annotations: ^0.1.0-dev.1

dev_dependencies:
  build_runner: ^2.4.8
  cli_gen: ^0.1.0-dev.1
  lints: ^3.0.0
  test: ^1.24.0

executables:
  dart_git: main
