name: cli_gen
repository: https://github.com/pattobrien/cli-gen

packages:
  - example
  - docs/pub_example
  - src/cli_annotations
  - src/cli_gen
  - src/cli_gen/test/**

scripts:
  analyze:
    exec: dart analyze .

  # to publish to pub.dev:
  # melos publish --no-dry-run
  # melos publish --dry-run

  publish:
    exec: dart publish

  test:
    exec: dart test

    packageFilters:
      published: true
  build:
    run: dart run build_runner build -d

  watch:
    run: dart run build_runner watch -d

ide:
  intellij:
    enabled: false
