name: cli_gen
repository: https://github.com/pattobrien/cli-gen

packages:
  - example
  - docs/pub_example
  - src/cli_annotations
  - src/cli_gen
  - src/cli_gen/test/**

scripts:
  analyze:
    exec: dart analyze .

  # to publish to pub.dev:
  # melos publish --no-dry-run

  publish:
    exec: dart publish --dry-run
  test:
    exec: dart test

ide:
  intellij:
    enabled: false
