name: workspace
description: The workspace for the cli_gen package.

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  cli_annotations: ^0.1.0-dev.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  cli_gen: ^0.1.0-dev.4
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  melos: ^4.1.0
  test: ^1.24.0

dependency_overrides:
  cli_gen:
    path: src/cli_gen
  cli_annotations:
    path: src/cli_annotations
