name: cli_gen_workspace
description: The workspace for the cli_gen package.

environment:
  sdk: ^3.5.0

workspace:
  - example
  - docs/pub_example
  - src/cli_annotations
  - src/cli_gen
  - test/goldens

dependencies:
  analyzer: ^6.8.0
  args: ^2.6.0
  cli_annotations: ^0.1.0-dev.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  cli_gen: ^0.1.0-dev.4
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^5.0.0
  melos: ^6.2.0
  test: ^1.25.9
