name: cli_gen
description: The workspace for the cli_gen package.

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
  melos: ^4.1.0
  test: ^1.24.0
