name: cli_annotations
description: |
  Annotations for building CLI applications using `package:cli_gen`.
version: 0.1.0-dev.6
homepage: https://github.com/pattobrien/cli-gen
repository: https://github.com/pattobrien/cli-gen
issue_tracker: https://github.com/pattobrien/cli-gen/issues

topics:
  - cli
  - args
  - codegen
  - macros

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  args: ^2.4.2
  meta: ^1.12.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^5.0.0
  test: ^1.24.0
