name: cli_annotations
description: A sample command-line application.
version: 0.1.0-dev.1

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
