name: pub_example
publish_to: none

environment:
  sdk: ^3.4.0-132.0.dev

dependencies:
  cli_annotations: ^0.1.0-dev.2

dev_dependencies:
  build_runner: ^2.4.8
  cli_gen: ^0.1.0-dev.2
  lints: ^3.0.0
  test: ^1.24.0
